### ISSUE TITLE
Driver field IBAN is Not Nullable without default

### ISSUE THREAD

**Issue by pg-goose** [pes2324q2-gei-upc/PowerPathFinder#23]
It is impossible to add a non-nullable field 'iban' to driver without specifying a default. This is because the database needs something to populate existing rows.
Either set it to be Null or Blank.

**Comment by LightBlue247** [comment]
I have set the field "iban" to null=True and blank=True. I'm not sure if it is necessary to put the "iban" when the user is registering or it can be placed in the edit profile screen too. If it is mandatory to fill the "iban" in the register screen I will need to delete the blank=True
